#!/usr/bin/env vite-node --script
import { readFile, writeFile } from "node:fs/promises";
import { findPackageJSON } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";

const webScript = await (async () => {
    const path = findPackageJSON("@types/web", import.meta.url)
    if (path == null) {
        throw new Error("Could not find @types/web package.json");
    }
    const fileURL = pathToFileURL(path);
    return await readFile(new URL("./index.d.ts", fileURL), "utf-8");
})()

const webModule = "// Generated by /scripts/generate.ts. DO NOT EDIT.\n\n" + webScript.replaceAll(/^((?:interface|type|declare namespace) )/gm, "export $1").replaceAll(/^(\/\/\/ <reference .*\/>)$/gm, "// $1");
{
    const fileURL = new URL("../src/types-web-module.d.ts", import.meta.url);
    await writeFile(fileURL, webModule);
}